
project_id = "owigcjycsaxmpsthjbrh"

[functions.create-payment-intent]
verify_jwt = true

[functions.packeta-points]
verify_jwt = true

[functions.create-order]
verify_jwt = true

[functions.create-checkout-session]
verify_jwt = true

[functions.verify-checkout-session]
verify_jwt = true

[functions.create-packeta-order]
verify_jwt = true

[functions.track-order]
verify_jwt = true
