[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = ""  # Disable functions

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 