[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 10

# Ensure Node.js is installed properly
[phases.setup]
nixPkgs = ["nodejs", "npm"]
aptPkgs = ["nodejs", "npm"]
cmds = ["node --version", "npm --version"] 