[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "node start.js"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"

[phases.setup]
nixPkgs = ["nodejs", "npm"] 